/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 07-sep-2024 13:16:04 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS agenciaseguro_idagencia_seq
;

DROP SEQUENCE IF EXISTS cobertura_idcobertura_seq
;

DROP SEQUENCE IF EXISTS companiareaseg_idcompania_seq
;

DROP SEQUENCE IF EXISTS estadopoliza_idestadopoliza_seq
;

DROP SEQUENCE IF EXISTS estadoreclamacion_idestadoreclamacion_seq
;

DROP SEQUENCE IF EXISTS poliza_numpoliza_seq
;

DROP SEQUENCE IF EXISTS reclamacion_numeroreclamacion_seq
;

DROP SEQUENCE IF EXISTS rol_idrol_seq
;

DROP SEQUENCE IF EXISTS seguro_idtiposeguro_seq
;

DROP SEQUENCE IF EXISTS siniestro_idsiniestro_seq
;

DROP SEQUENCE IF EXISTS usuario_idusuario_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS AgenciaSeguro CASCADE
;

DROP TABLE IF EXISTS Cliente CASCADE
;

DROP TABLE IF EXISTS Cobertura CASCADE
;

DROP TABLE IF EXISTS CompaniaReaseg CASCADE
;

DROP TABLE IF EXISTS EstadoPoliza CASCADE
;

DROP TABLE IF EXISTS EstadoReclamacion CASCADE
;

DROP TABLE IF EXISTS Poliza CASCADE
;

DROP TABLE IF EXISTS Reclamacion CASCADE
;

DROP TABLE IF EXISTS Rol CASCADE
;

DROP TABLE IF EXISTS Seguro CASCADE
;

DROP TABLE IF EXISTS Siniestro CASCADE
;

DROP TABLE IF EXISTS Usuario CASCADE
;

/* Create Tables */

CREATE TABLE AgenciaSeguro
(
	idAgencia integer NOT NULL   DEFAULT NEXTVAL(('"agenciaseguro_idagencia_seq"'::text)::regclass),
	nombreAgencia varchar(50) NOT NULL,
	direccionPostal varchar(50) NOT NULL,
	telefono varchar(50) NOT NULL,
	correoElectronico varchar(50) NOT NULL,
	idTipoSeguro integer NOT NULL,
	directorGeneral varchar(50) NOT NULL,
	jefeDepartamentoSeguros varchar(50) NOT NULL,
	jefeDepartamentoReclamaciones varchar(50) NOT NULL
)
;

CREATE TABLE Cliente
(
	id varchar(50) NOT NULL,
	sexo char(2) NOT NULL,
	nombre varchar(50) NOT NULL,
	apellidos varchar(50) NOT NULL,
	edad integer NOT NULL,
	direccionPostal varchar(50) NOT NULL,
	telefono varchar(50) NOT NULL,
	correoElectronico varchar(50) NOT NULL,
	pais varchar(50) NOT NULL
)
;

CREATE TABLE Cobertura
(
	idCobertura integer NOT NULL   DEFAULT NEXTVAL(('"cobertura_idcobertura_seq"'::text)::regclass),
	tipoCobertura varchar(50) NOT NULL
)
;

CREATE TABLE CompaniaReaseg
(
	idCompania integer NOT NULL   DEFAULT NEXTVAL(('"companiareaseg_idcompania_seq"'::text)::regclass),
	nombreCompania varchar(50) NOT NULL,
	paisOrigen varchar(50) NOT NULL,
	tipoReaseg varchar(50) NOT NULL,
	porcentajeParticipacion double precision NOT NULL,
	idAgencia integer NOT NULL
)
;

CREATE TABLE EstadoPoliza
(
	idEstadoPoliza integer NOT NULL   DEFAULT NEXTVAL(('"estadopoliza_idestadopoliza_seq"'::text)::regclass),
	tipoPoliza varchar(50) NOT NULL,
	motivo varchar(255) NULL
)
;

CREATE TABLE EstadoReclamacion
(
	idEstadoReclamacion integer NOT NULL   DEFAULT NEXTVAL(('"estadoreclamacion_idestadoreclamacion_seq"'::text)::regclass),
	tipoReclamacion varchar(50) NOT NULL,
	motivo varchar(255) NULL
)
;

CREATE TABLE Poliza
(
	numPoliza integer NOT NULL   DEFAULT NEXTVAL(('"poliza_numpoliza_seq"'::text)::regclass),
	fechaInicio date NOT NULL,
	fechaFin date NOT NULL,
	primaMensual double precision NOT NULL,
	montoTotal double precision NOT NULL,
	idAgencia integer NOT NULL,
	id varchar(50) NOT NULL,
	idEstadoPoliza integer NOT NULL,
	idCobertura integer NOT NULL
)
;

CREATE TABLE Reclamacion
(
	numeroReclamacion integer NOT NULL   DEFAULT NEXTVAL(('"reclamacion_numeroreclamacion_seq"'::text)::regclass),
	fechaSiniestro date NOT NULL,
	montoReclamado double precision NOT NULL,
	montoIndemnizado double precision NOT NULL,
	numPoliza integer NOT NULL,
	idEstadoReclamacion integer NOT NULL,
	idSiniestro integer NOT NULL
)
;

CREATE TABLE Rol
(
	idRol integer NOT NULL   DEFAULT NEXTVAL(('"rol_idrol_seq"'::text)::regclass),
	nombreRol varchar(50) NOT NULL
)
;

CREATE TABLE Seguro
(
	idTipoSeguro integer NOT NULL   DEFAULT NEXTVAL(('"seguro_idtiposeguro_seq"'::text)::regclass),
	tipo varchar(50) NOT NULL
)
;

CREATE TABLE Siniestro
(
	idSiniestro integer NOT NULL   DEFAULT NEXTVAL(('"siniestro_idsiniestro_seq"'::text)::regclass),
	tipoSiniestro varchar(50) NOT NULL
)
;

CREATE TABLE Usuario
(
	idUsuario integer NOT NULL   DEFAULT NEXTVAL(('"usuario_idusuario_seq"'::text)::regclass),
	nombreUsuario varchar(255) NOT NULL,
	contrasena varchar(255) NOT NULL,
	idRol integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE AgenciaSeguro ADD CONSTRAINT llavePrimariaAgenciaSeguro
	PRIMARY KEY (idAgencia)
;

CREATE INDEX IXFK_AgenciaSeguro_Seguro ON AgenciaSeguro (idTipoSeguro ASC)
;

ALTER TABLE Cliente ADD CONSTRAINT llavePrimariaCliente
	PRIMARY KEY (id)
;

ALTER TABLE Cobertura ADD CONSTRAINT PK_Cobertura
	PRIMARY KEY (idCobertura)
;

ALTER TABLE CompaniaReaseg ADD CONSTRAINT llavePrimariaCompaniaReaseg
	PRIMARY KEY (idCompania)
;

CREATE INDEX IXFK_CompaniaReaseg_AgenciaSeguro ON CompaniaReaseg (idAgencia ASC)
;

ALTER TABLE EstadoPoliza ADD CONSTRAINT llavePrimariaEstadoPoliza
	PRIMARY KEY (idEstadoPoliza)
;

ALTER TABLE EstadoReclamacion ADD CONSTRAINT llavePrimariaEstadoReclamacion
	PRIMARY KEY (idEstadoReclamacion)
;

ALTER TABLE Poliza ADD CONSTRAINT llavePrimariaPoliza
	PRIMARY KEY (numPoliza)
;

CREATE INDEX IXFK_Poliza_AgenciaSeguro ON Poliza (idAgencia ASC)
;

CREATE INDEX IXFK_Poliza_Cliente ON Poliza (id ASC)
;

CREATE INDEX IXFK_Poliza_Cobertura ON Poliza (idCobertura ASC)
;

CREATE INDEX IXFK_Poliza_EstadoPoliza ON Poliza (idEstadoPoliza ASC)
;

ALTER TABLE Reclamacion ADD CONSTRAINT llavePrimariaReclamacion
	PRIMARY KEY (numeroReclamacion)
;

CREATE INDEX IXFK_Reclamacion_EstadoReclamacion ON Reclamacion (idEstadoReclamacion ASC)
;

CREATE INDEX IXFK_Reclamacion_Poliza ON Reclamacion (numPoliza ASC)
;

CREATE INDEX IXFK_Reclamacion_Siniestro ON Reclamacion (idSiniestro ASC)
;

ALTER TABLE Rol ADD CONSTRAINT llavePrimariaRol
	PRIMARY KEY (idRol)
;

ALTER TABLE Seguro ADD CONSTRAINT llavePrimariaTipoSeguro
	PRIMARY KEY (idTipoSeguro)
;

ALTER TABLE Siniestro ADD CONSTRAINT llavePrimariaSiniestro
	PRIMARY KEY (idSiniestro)
;

ALTER TABLE Usuario ADD CONSTRAINT llavePrimariaUsuario
	PRIMARY KEY (idUsuario)
;

CREATE INDEX IXFK_Usuario_Rol ON Usuario (idRol ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE AgenciaSeguro ADD CONSTRAINT FK_AgenciaSeguro_Seguro
	FOREIGN KEY (idTipoSeguro) REFERENCES Seguro (idTipoSeguro) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Poliza ADD CONSTRAINT FK_Poliza_AgenciaSeguro
	FOREIGN KEY (idAgencia) REFERENCES AgenciaSeguro (idAgencia) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Poliza ADD CONSTRAINT FK_Poliza_Cliente
	FOREIGN KEY (id) REFERENCES Cliente (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Poliza ADD CONSTRAINT FK_Poliza_Cobertura
	FOREIGN KEY (idCobertura) REFERENCES Cobertura (idCobertura) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Poliza ADD CONSTRAINT FK_Poliza_EstadoPoliza
	FOREIGN KEY (idEstadoPoliza) REFERENCES EstadoPoliza (idEstadoPoliza) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Reclamacion ADD CONSTRAINT FK_Reclamacion_EstadoReclamacion
	FOREIGN KEY (idEstadoReclamacion) REFERENCES EstadoReclamacion (idEstadoReclamacion) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Reclamacion ADD CONSTRAINT FK_Reclamacion_Poliza
	FOREIGN KEY (numPoliza) REFERENCES Poliza (numPoliza) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Reclamacion ADD CONSTRAINT FK_Reclamacion_Siniestro
	FOREIGN KEY (idSiniestro) REFERENCES Siniestro (idSiniestro) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Usuario ADD CONSTRAINT FK_Usuario_Rol
	FOREIGN KEY (idRol) REFERENCES Rol (idRol) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE agenciaseguro_idagencia_seq INCREMENT 1 START 1
;

CREATE SEQUENCE cobertura_idcobertura_seq INCREMENT 1 START 1
;

CREATE SEQUENCE companiareaseg_idcompania_seq INCREMENT 1 START 1
;

CREATE SEQUENCE estadopoliza_idestadopoliza_seq INCREMENT 1 START 1
;

CREATE SEQUENCE estadoreclamacion_idestadoreclamacion_seq INCREMENT 1 START 1
;

CREATE SEQUENCE poliza_numpoliza_seq INCREMENT 1 START 1
;

CREATE SEQUENCE reclamacion_numeroreclamacion_seq INCREMENT 1 START 1
;

CREATE SEQUENCE rol_idrol_seq INCREMENT 1 START 1
;

CREATE SEQUENCE seguro_idtiposeguro_seq INCREMENT 1 START 1
;

CREATE SEQUENCE siniestro_idsiniestro_seq INCREMENT 1 START 1
;

CREATE SEQUENCE usuario_idusuario_seq INCREMENT 1 START 1
;
